// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenFile(arg1) {
  window['go']['main']['App']['OpenFile'](arg1);
}
